name: Release

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  publish-to-dockerhub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: khose
      IMAGE: dev-container-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REPO }}/${{ env.IMAGE }}:${{ github.ref_name }}
        context: .
    - name: Build image and push to Docker Hub for latest label
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REPO }}/${{ env.IMAGE }}:latest
        context: .
    - name: Update docker repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ env.REPO }}/${{ env.IMAGE }}
        readme-filepath: README.md
